server:
  port: 8005

spring:
  application:
    name: msvc-auth
  config:
    import: configserver:http://localhost:8888/ # Importa la configuraci贸n desde el Config Server

application-title: msvc-auth

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka # Direcci贸n del servidor Eureka
    register-with-eureka: true # Registrar este servicio en Eureka
    fetch-registry: true # Obtener informaci贸n de otros servicios registrados en Eureka

logging:
  level:
    root: INFO
    com.example.msvc-auth: DEBUG # Ajusta el nivel de logs para facilitar la depuraci贸n del servicio
