server:
  port: 8005

spring:
  application:
    name: msvc-auth
  config:
    import: configserver:http://config-server:8888/ # Importa la configuración desde el Config Server

application-title: msvc-auth

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: localhost

logging:
  level:
    root: INFO
    com.example.msvc-auth: DEBUG # Ajusta el nivel de logs para facilitar la depuración del servicio
