server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  config:
    import: configserver:http://localhost:8888/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        connect-timeout: 60000
        response-timeout: 60s