server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  config:
    import: configserver:http://config-server:8888/ # Importa la configuraci칩n desde el Config Server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Habilita la resoluci칩n de rutas din치micas mediante Eureka
      httpclient:
        connect-timeout: 60000 # Tiempo de espera de conexi칩n en milisegundos
        response-timeout: 60s # Tiempo de espera para la respuesta en segundos

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: localhost
