server:
  port: 8004

spring:
  application:
    name: msvc-user
  config:
    import: configserver:http://config-server:8888/ # Importa la configuraci贸n desde el Config Server

application-title: msvc-user

eureka:
  client:
    service-url:
      default-zone: http://eureka-server:8761/ # Direcci贸n del servidor Eureka
    register-with-eureka: true # Registrar este servicio en Eureka
    fetch-registry: true # Obtener informaci贸n de otros servicios registrados en Eureka

logging:
  level:
    root: INFO
    com.example.msvc-user: DEBUG # Ajusta el nivel de logs para facilitar la depuraci贸n del servicio
