server:
  port: 8004

spring:
  application:
    name: msvc-user
  config:
    import: configserver:http://config-server:8888/ # Importa la configuración desde el Config Server

application-title: msvc-user

eureka:
  client:
    fetch-registry: true
    register-whit-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost
