spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
  datasource:
    url: jdbc:postgresql://postgres:5432/microservice
    username: POSTGRES_USER:postgres
    password: POSTGRES_PASSWORD:55

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: :http://localhost:8761/eureka

application-description: Its Done UK Application
application-license: API Licence
application-version: 1.0
