spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
  datasource:
    url: jdbc:postgresql://postgres:5432/microservice
    username: postgres
    password: 55

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: localhost

application-description: Its Done UK Application
application-license: API Licence
application-version: 1.0
