spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Raulcudris/arquictetura-microservicios-spring.git
          search-paths: config

server:
  port: 8888
